# Generated by Django 2.2.6 on 2020-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='settings.Language'),
        ),
    ]
