# Generated by Django 2.2.6 on 2020-04-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='languages',
        ),
    ]
