# Generated by Django 2.2.6 on 2020-05-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20200430_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='completed',
        ),
    ]
