# Generated by Django 2.2.10 on 2020-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
