# Generated by Django 2.2.10 on 2020-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20200503_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='status_success',
            field=models.IntegerField(null=True),
        ),
    ]
