# Generated by Django 2.2.10 on 2020-05-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20200503_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Configuration'),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
    ]
