# Generated by Django 2.2.10 on 2020-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20200503_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_detail',
            field=models.ManyToManyField(blank=True, null=True, through='message.MessageStatus', to='settings.Configuration'),
        ),
    ]
