# Generated by Django 2.2.10 on 2020-05-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20200503_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Configuration'),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='status_error',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='status_success',
            field=models.IntegerField(null=True),
        ),
    ]
