# Generated by Django 2.2.10 on 2020-05-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20200503_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestatus',
            old_name='status_error',
            new_name='error_count',
        ),
        migrations.RenameField(
            model_name='messagestatus',
            old_name='status_success',
            new_name='success_count',
        ),
    ]
