# Generated by Django 2.2.10 on 2020-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_auto_20200503_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatus',
            name='config_error',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='error_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='success_count',
            field=models.IntegerField(),
        ),
    ]
