# Generated by Django 3.2.12 on 2022-05-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetdataelement',
            name='compulsory_category_combo',
        ),
        migrations.AddField(
            model_name='datasetdataelement',
            name='category_option_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categoryoptioncombo'),
        ),
        migrations.AddField(
            model_name='datasetdataelement',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetdataelement',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
    ]
