# Generated by Django 3.2.12 on 2022-02-11 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0004_auto_20220211_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis2user',
            name='version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
