# Generated by Django 3.2.12 on 2022-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0005_categoryoptioncombo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycombo',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='categoryoptioncombo',
            options={'ordering': ['name']},
        ),
    ]
