# Generated by Django 3.2.12 on 2022-02-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0005_auto_20220211_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhis2user',
            old_name='orgUnits',
            new_name='org_units',
        ),
    ]
