# Generated by Django 3.2.12 on 2022-02-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0006_auto_20220213_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='category_combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categorycombo'),
        ),
    ]
