# Generated by Django 3.2.12 on 2022-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0007_dataelement_category_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_element',
            field=models.ManyToManyField(to='dhis.DataElement'),
        ),
    ]
