# Generated by Django 3.2.12 on 2022-02-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhis', '0008_auto_20220214_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('section_id', models.CharField(max_length=40, unique=True)),
                ('sort_order', models.IntegerField()),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionDataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sectiondataelement', to=settings.AUTH_USER_MODEL)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.section')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sectiondataelement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='data_element',
            field=models.ManyToManyField(through='dhis.SectionDataElement', to='dhis.DataElement'),
        ),
        migrations.AddField(
            model_name='section',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset'),
        ),
        migrations.AddField(
            model_name='section',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_section', to=settings.AUTH_USER_MODEL),
        ),
    ]
