# Generated by Django 3.2.12 on 2022-02-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0008_rename_ds_id_dataset_dataset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgunit',
            old_name='ou_id',
            new_name='org_unit_id',
        ),
    ]
