# Generated by Django 3.2.12 on 2022-02-14 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0009_auto_20220214_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondataelement',
            name='version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
