# Generated by Django 3.2.12 on 2022-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0010_sectiondataelement_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2user',
            name='passcode',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
