# Generated by Django 3.2.12 on 2022-02-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0013_auto_20220215_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='version',
        ),
    ]
