# Generated by Django 3.2.12 on 2022-02-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0014_remove_usergroup_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sort_order']},
        ),
    ]
