# Generated by Django 3.2.12 on 2022-02-23 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhis', '0017_dataset_open_future_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Synced', 'Synced')], default='Pending', max_length=8)),
                ('category_option_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.categoryoptioncombo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datavalue', to=settings.AUTH_USER_MODEL)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.orgunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datavalue', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dhis2user')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
