# Generated by Django 3.2.12 on 2022-02-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0018_datavalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='category_option_combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categoryoptioncombo'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='data_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='data_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.orgunit'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dhis2user'),
        ),
    ]
