# Generated by Django 3.2.12 on 2022-02-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0020_auto_20220224_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalue',
            name='data_value_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.datavalueset'),
        ),
        migrations.AlterField(
            model_name='datavalueset',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datavalueset',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
