# Generated by Django 3.2.12 on 2022-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0021_auto_20220224_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalue',
            name='session_id',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
