# Generated by Django 3.2.12 on 2022-02-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0022_datavalue_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalueset',
            name='mark_as_complete',
            field=models.BooleanField(default=False),
        ),
    ]
