# Generated by Django 2.2.6 on 2020-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
