# Generated by Django 2.2.10 on 2020-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_auto_20200429_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
