export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_TIMER = "AUTH_SET_TIMER";

export const FETCH_LANGUAGES_START = "FETCH_LANGUAGES_START";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";
export const SAVE_LANGUAGE_SUCCESS = "SAVE_LANGUAGE_SUCCESS";
export const RESET_SAVE_LANGUAGE_SUCCESS = "RESET_SAVE_LANGUAGE_SUCCESS";
export const FETCH_LANGUAGE_START = "FETCH_LANGUAGE_START";
export const FETCH_LANGUAGE_SUCCESS = "FETCH_LANGUAGE_SUCCESS";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const UPDATE_LANGUAGE_FAIL = "UPDATE_LANGUAGE_FAIL";
export const FETCH_LANGUAGES_LOOKUP_START = "FETCH_LANGUAGES_LOOKUP_START";
export const FETCH_LANGUAGES_LOOKUP_SUCCESS = "FETCH_LANGUAGES_LOOKUP_SUCCESS";
export const FETCH_LANGUAGES_LOOKUP_FAIL = "FETCH_LANGUAGES_LOOKUP_FAIL";

export const FETCH_SUBSCRIBERS_START = "FETCH_SUBSCRIBERS_START";
export const FETCH_SUBSCRIBERS_SUCCESS = "FETCH_SUBSCRIBERS_SUCCESS";
export const FETCH_SUBSCRIBERS_FAIL = "FETCH_SUBSCRIBERS_FAIL";
export const SAVE_SUBSCRIBER_SUCCESS = "SAVE_SUBSCRIBER_SUCCESS";
export const RESET_SAVE_SUBSCRIBER_SUCCESS = "RESET_SAVE_SUBSCRIBER_SUCCESS";
export const FETCH_SUBSCRIBER_START = "FETCH_SUBSCRIBER_START";
export const FETCH_SUBSCRIBER_SUCCESS = "FETCH_SUBSCRIBER_SUCCESS";
export const REMOVE_SUBSCRIBER = "REMOVE_SUBSCRIBER";
export const UPDATE_SUBSCRIBER_FAIL = "UPDATE_SUBSCRIBER_FAIL";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";
export const SAVE_MESSAGE_SUCCESS = "SAVE_MESSAGE_SUCCESS";
export const RESET_SAVE_MESSAGE_SUCCESS = "RESET_SAVE_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_START = "FETCH_MESSAGE_START";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const UPDATE_MESSAGE_FAIL = "UPDATE_MESSAGE_FAIL";
export const CHANGE_MESSAGE_STATUS = "CHANGE_MESSAGE_STATUS";

export const FETCH_CHANNELS_LOOKUP_START = "FETCH_CHANNELS_LOOKUP_START";
export const FETCH_CHANNELS_LOOKUP_SUCCESS = "FETCH_CHANNELS_LOOKUP_SUCCESS";
export const FETCH_CHANNELS_LOOKUP_FAIL = "FETCH_CHANNELS_LOOKUP_FAIL";

export const FETCH_SURVEYS_START = "FETCH_SURVEYS_START";
export const FETCH_SURVEYS_SUCCESS = "FETCH_SURVEYS_SUCCESS";
export const FETCH_SURVEYS_FAIL = "FETCH_SURVEYS_FAIL";
export const SAVE_SURVEY_SUCCESS = "SAVE_SURVEY_SUCCESS";
export const RESET_SAVE_SURVEY_SUCCESS = "RESET_SAVE_SURVEY_SUCCESS";
export const FETCH_SURVEY_START = "FETCH_SURVEY_START";
export const FETCH_SURVEY_SUCCESS = "FETCH_SURVEY_SUCCESS";
export const REMOVE_SURVEY = "REMOVE_SURVEY";
export const UPDATE_SURVEY_FAIL = "UPDATE_SURVEY_FAIL";

export const FETCH_RESULTS_START = "FETCH_RESULTS_START";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_FAIL = "FETCH_RESULTS_FAIL";
export const DELETE_RESULT_SUCCESS = "DELETE_RESULT_SUCCESS";
export const REMOVE_RESULT = "REMOVE_RESULT";
export const RESET_DELETE_RESULT_SUCCESS = "RESET_DELETE_RESULT_SUCCESS";

export const FETCH_DASHBOARD_DATA_START = "FETCH_DASHBOARD_DATA_START";
export const FETCH_DASHBOARD_DATA_SUCCESS = "FETCH_DASHBOARD_DATA_SUCCESS";
export const FETCH_DASHBOARD_DATA_FAIL = "FETCH_DASHBOARD_DATA_FAIL";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
