apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: belendia/flare:IMAGE_TAG
          imagePullPolicy: Always
          command:
            [
              "/bin/sh",
              "-c",
              "celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler",
            ]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DEBUG
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: DB_PORT
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: REDIS_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: REDIS_PORT
            - name: INSTITUTE_NAME
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: INSTITUTE_NAME
            - name: KEY_EXPIRE_AFTER
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: KEY_EXPIRE_AFTER
            - name: MENU_ITEMS_SIZE
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: MENU_ITEMS_SIZE
            - name: LINODE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: LINODE_BUCKET
            - name: LINODE_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: LINODE_BUCKET_REGION
            - name: LINODE_BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: LINODE_BUCKET_ACCESS_KEY
            - name: LINODE_BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flare-secret
                  key: LINODE_BUCKET_SECRET_KEY
