primary:
  persistence:
    enabled: true
  extendedConfiguration: |
    max_connections=100
    shared_buffers= 1GB
    effective_cache_size= 3GB
    maintenance_work_mem= 256MB
    checkpoint_completion_target= 0.9
    wal_buffers= 16MB
    default_statistics_target= 100
  pgHbaConfiguration: |
    hostssl  all             all             0.0.0.0/0               trust
    host     all             all             0.0.0.0/0               trust
    local    all             all                                     trust
    host     all             all        127.0.0.1/32                 trust
    host     replication     all             0.0.0.0/0               trust
global:
  postgresql:
    auth:
      postgresPassword: "Mt731B$hun$k5Y0rZt$$&CM6Z"
      username: "flare"
      password: "Mt731B$hun$k5Y0rZt$$&CM6Z"
      database: "flare"
