# Generated by Django 2.2.6 on 2020-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_message_languages'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='message.Message'),
        ),
    ]
