# Generated by Django 2.2.10 on 2020-05-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200502_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Language'),
        ),
    ]
