# Generated by Django 2.2.10 on 2020-05-05 12:33

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200429_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='published',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='yaml_file',
        ),
        migrations.AddField(
            model_name='survey',
            name='journeys',
            field=models.FileField(default=1, storage=survey.models.OverwriteStorage(), upload_to='journeys'),
            preserve_default=False,
        ),
    ]
