# Generated by Django 2.2.10 on 2020-05-05 13:14

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200505_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='journeys',
            field=models.FileField(storage=survey.models.OverwriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
