# Generated by Django 2.2.10 on 2020-05-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200505_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='gateway',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='survey',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
