# Generated by Django 2.2.10 on 2020-05-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200509_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='gateway',
            new_name='endpoint',
        ),
    ]
