# Generated by Django 2.2.10 on 2020-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200509_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
