# Generated by Django 2.2.10 on 2020-05-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_survey_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='journeys',
        ),
    ]
