# Generated by Django 2.2.10 on 2020-05-09 17:05

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200509_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='survey',
            name='journeys',
            field=models.FileField(default=1, storage=survey.models.OverwriteStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
