# Generated by Django 2.2.10 on 2020-05-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_surveyresult_result_copied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='result_copied',
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='rejected',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='posted',
            field=models.BooleanField(null=True),
        ),
    ]
