name: Build Flare Container & Push to DockerHub registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_flare_job:
    # Call the flare-test.yaml workflow and wait until it finishes testing
    uses: PATH-Global-Health/flare/.github/workflows/flare-test.yaml@main
  build:
    runs-on: ubuntu-latest
    # Complete test_flare_job before running build_lare_job
    needs: [test_flare_job]
    env:
      SECRET_KEY: test-key-for-testing-only

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container image
        working-directory: ./flare
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f Dockerfile.prod \
            -t belendia/flare:${GITHUB_SHA::7} \
            -t belendia/flare:latest .
      - name: Push image
        run: |
          docker push belendia/flare --all-tags
      - name: Install Linode CLI
        uses: linode/action-linode-cli@v1
        with:
          token: ${{ secrets.LINODE_TOKEN }}
      - name: Update deployment secrets
        env:
          LINODE_CLUSTER: Macepa-Ethiopia
        run: |
          linode-cli k8s context-switch $LINODE_CLUSTER
          cat << EOF >> flare/.env.prod
          DEBUG=${{ secrets.DEBUG }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          KEY_EXPIRE_AFTER=${{ secrets.KEY_EXPIRE_AFTER }}
          INSTITUTE_NAME=${{ secrets.INSTITUTE_NAME }}
          MENU_ITEMS_SIZE=${{ secrets.MENU_ITEMS_SIZE }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF
          kubectl delete secret flare-secret
          kubectl create secret generic flare-secret --from-env-file=flare/.env.prod
