name: Build Flare Container & Push to DockerHub registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_flare_job:
    # Call the flare-test.yaml workflow and wait until it finishes testing
    uses: PATH-Global-Health/flare/.github/workflows/flare-test.yaml@main
  build:
    runs-on: ubuntu-latest
    # Complete test_flare_job before running build_lare_job
    needs: [test_flare_job]
    env:
      SECRET_KEY: test-key-for-testing-only

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container image
        working-directory: ./flare
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f Dockerfile.prod \
            -t belendia/flare:${GITHUB_SHA::7} \
            -t belendia/flare:latest .
      - name: Push image
        run: |
          docker push belendia/flare --all-tags
