# Generated by Django 3.2.16 on 2022-11-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_combo_id', models.CharField(max_length=40, unique=True)),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categorycombo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_option_combo_id', models.CharField(max_length=40)),
                ('version', models.UUIDField()),
                ('category_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.categorycombo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categoryoptioncombo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('data_element_id', models.CharField(max_length=40, unique=True)),
                ('value_type', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.UUIDField()),
                ('category_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categorycombo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dataelement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dataset_id', models.CharField(max_length=40, unique=True)),
                ('period_type', models.CharField(blank=True, max_length=50, null=True)),
                ('open_future_periods', models.IntegerField(default=0)),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dataset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=400)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instance', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_instance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('section_id', models.CharField(max_length=40, unique=True)),
                ('sort_order', models.IntegerField()),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_id', models.CharField(max_length=40, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usergroup', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.instance')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_usergroup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionDataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sectiondataelement', to=settings.AUTH_USER_MODEL)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.section')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sectiondataelement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='data_element',
            field=models.ManyToManyField(through='dhis.SectionDataElement', to='dhis.DataElement'),
        ),
        migrations.AddField(
            model_name='section',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset'),
        ),
        migrations.AddField(
            model_name='section',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('org_unit_id', models.CharField(max_length=40, unique=True)),
                ('parent', models.CharField(max_length=40)),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orgunit', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orgunit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DHIS2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=30, null=True, unique=True)),
                ('version', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dhis2user', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.usergroup')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance')),
                ('org_units', models.ManyToManyField(to='dhis.OrgUnit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dhis2user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataValueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('period', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('mark_as_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Synced', 'Synced')], default='Pending', max_length=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datavalueset', to=settings.AUTH_USER_MODEL)),
                ('data_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset')),
                ('org_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.orgunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datavalueset', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dhis2user')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, max_length=240, null=True)),
                ('category_option_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categoryoptioncombo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datavalue', to=settings.AUTH_USER_MODEL)),
                ('data_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement')),
                ('data_value_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.datavalueset')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datavalue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DatasetDataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('compulsory', models.BooleanField(default=False)),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('category_option_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.categoryoptioncombo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasetdataelement', to=settings.AUTH_USER_MODEL)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataelement')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.dataset')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.instance')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_datasetdataelement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_element',
            field=models.ManyToManyField(through='dhis.DatasetDataElement', to='dhis.DataElement'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='org_units',
            field=models.ManyToManyField(to='dhis.OrgUnit'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dataset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dataelement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryoptioncombo',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='categoryoptioncombo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categoryoptioncombo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorycombo',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis.instance'),
        ),
        migrations.AddField(
            model_name='categorycombo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categorycombo', to=settings.AUTH_USER_MODEL),
        ),
    ]
