# Generated by Django 3.2.16 on 2022-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoptioncombo',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='categoryoptioncombo',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
