# Generated by Django 3.2.16 on 2022-11-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0002_auto_20221104_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='data_element',
        ),
        migrations.AddField(
            model_name='datasetdataelement',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis.section'),
        ),
        migrations.AddField(
            model_name='datasetdataelement',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SectionDataElement',
        ),
    ]
