# Generated by Django 3.2.20 on 2023-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis', '0006_auto_20230705_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdataelement',
            name='initialize_with_zero',
            field=models.BooleanField(default=True),
        ),
    ]
